prometheus:
  prometheusSpec:
    # This configuration enables prometheus to monitor other namespaces
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

grafana:
  enabled: true
  adminPassword: admin
  grafana.ini:
    server:
      root_url: http://localhost/grafana
      serve_from_sub_path: true