replicaCount: 1

namespace: weather

image: dotnet-weather-service

service:
  type: ClusterIP
  port: 80

healthcheck:
  path: /health

prometheus:
  path: /metrics

ingress:
  path: /forecast

resources:
  requests:
    memory: 50Mi
    cpu: 10m
  limits:
    memory: 100Mi
    cpu: 50m