apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ required "" .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        name: {{ .Release.Name }}
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: {{ required "" .Values.resources.requests.memory }}
              cpu: {{ required "" .Values.resources.requests.cpu }}
            limits:
              memory: {{ required "" .Values.resources.limits.memory }}
              cpu: {{ required "" .Values.resources.limits.cpu }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ required "" .Values.healthcheck.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ required "" .Values.healthcheck.path }}
              port: http
