---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: logging
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    [PARSER]
        Name        log_parse
        Format      json
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker_no_time
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
    [FILTER]
        Name parser
        Match *
        Key_Name          log
        Parser            log_parse
        Reserve_Data      True
    [OUTPUT]
        Name            es
        Match           *
        Host            opensearch-cluster-master.logging.svc.cluster.local
        Port            9200
        HTTP_User       admin
        HTTP_Passwd     admin
        Logstash_Format On
        Logstash_Prefix fluentbit
        Replace_Dots    On
        Retry_Limit     5
        tls             On
        tls.verify      Off
        Generate_ID     On
        Buffer_Size     2MB
        Suppress_Type_Name On
